version: "3.7"

services:
  # ticket-system:
  #   depends_on:
  #     - postgres
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - DATABASE_HOSTNAME=postgres
  #     - DATABASE_PORT=5432

  postgres-default:
    image: "postgres"
    environment:
      - POSTGRES_DB=ticket_system_default
      - POSTGRES_USER=ticket_system
      - POSTGRES_PASSWORD=ticketpass
    ports:
      - "5432:5432"

  postgres-shared:
    image: "postgres"
    environment:
      - POSTGRES_DB=ticket_system_shared
      - POSTGRES_USER=ticket_system
      - POSTGRES_PASSWORD=ticketpass
    ports:
      - "5433:5432"


  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - postgres-default
      - postgres-shared
    command: postgres-default:5432
