apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: postgres-shared
  name: postgres-shared
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: postgres-shared
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: ticket_system_shared
        - name: POSTGRES_PASSWORD
          value: ticketpass
        - name: POSTGRES_USER
          value: ticket_system
        image: postgres
        name: postgres-shared
        resources: {}
      restartPolicy: Always
status: {}
