version: "3"

services:
  ticket-system:
    image: gcr.io/stone-net-260315/ticket-system:v0.1
    depends_on:
      - postgres-default
      - postgres-shared
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOSTNAME_DEFAULT=postgres-default
      - DATABASE_HOSTNAME_SHARED=postgres-shared
      - DATABASE_PORT_DEFAULT=5433
      - DATABASE_PORT_SHARED=5434

  postgres-default:
    image: "postgres"
    volumes:
      - ~/postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ticket_system_default
      - POSTGRES_USER=ticket_system
      - POSTGRES_PASSWORD=ticketpass

  postgres-shared:
    image: "postgres"
    environment:
      - POSTGRES_DB=ticket_system_shared
      - POSTGRES_USER=ticket_system
      - POSTGRES_PASSWORD=ticketpass

  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - postgres-default
      - postgres-shared
    command:
      - postgres-default:5432
      - postgres-shared:5432
