apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: start-dependencies
  name: start-dependencies
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: start-dependencies
    spec:
      containers:
      - args:
        - postgres-default:5432
        - postgres-shared:5432
        image: dadarek/wait-for-dependencies
        name: start-dependencies
        resources: {}
      restartPolicy: Always
status: {}
