apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: ticket-system
  name: ticket-system
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: ticket-system
    spec:
      containers:
      - env:
        - name: DATABASE_HOSTNAME_DEFAULT
          value: postgres-default
        - name: DATABASE_HOSTNAME_SHARED
          value: postgres-shared
        - name: DATABASE_PORT_DEFAULT
          value: "5433"
        - name: DATABASE_PORT_SHARED
          value: "5434"
        image: gcr.io/stone-net-260315/ticket-system:v0.1
        name: ticket-system
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
